# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce69177f65d86ec5ff7f31cd44693102d921ff1b6accb6df942c373911a02ccb44a524bd115afaaefcfffd2b8b7d07c074f11faf35e13161bfb0bbb1e3402c1c

test:
  secret_key_base: 7d8c1f0df018e30dd6cfb36b8798d02f6b6aa653e7f494f6dba182ecf07c4533d13e3d09091b3c24d78041383f65cafa689f614a6b88f8bbba6f87849170776d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
